//AUTOGENERATED FILE FROM png2mtspr
#define agent_TILE_H 8
#define agent_WIDTH 16
#define agent_HEIGHT 16
#define agent_PIVOT_X 8
#define agent_PIVOT_Y 8

extern const UINT8 agent_data[160];
extern const metasprite_t* const agent_metasprites[5];
