//AUTOGENERATED FILE FROM png2mtspr
#define spieler_TILE_H 8
#define spieler_WIDTH 16
#define spieler_HEIGHT 16
#define spieler_PIVOT_X 8
#define spieler_PIVOT_Y 8

extern const UINT8 spieler_data[176];
extern const metasprite_t* const spieler_metasprites[6];
